name: learn github actions
run-name: ${{ github.actor }} is learning Github Actions
on: [ push ]

jobs:
  check-version:
    environment: albano-gce-instance
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - run: ./gradlew bootJar
      - run: ls -al
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.GCE_INSTANCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          rm: true
          source: build/libs/gh-actions-gcp-sample-0.0.1-SNAPSHOT.jar
          target: /home/${{ secrets.GCE_USER }}/app/gh-actions-gcp-sample-0.0.1-SNAPSHOT.jar
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCE_INSTANCE_HOST }}
          username: ${{ secrets.GCE_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          script: java -jar /home/${{ secrets.GCE_USER }}/app/build/libs/gh-actions-gcp-sample-0.0.1-SNAPSHOT.jar
        