name: learn github actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]

jobs:
  check-version:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: executing remote ssh commands using key
      uses: appleboy/ssh-actions@v1.0.3
      with:
        host: ${{ secrets.GCE_INSTANCE_HOST }}
        username: ${{ secrets.GCE_USER }}
        key: ${{ secrets.GCE_SSH_KEY }}
        script: whoami
