name: learn github actions
run-name: ${{ github.actor }} is learning Github Actions
on: [push]

jobs:
  check-version:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: ssh-scp-ssh-pipelines
      uses: cross-the-world/ssh-scp-ssh-pipelines@v1.1.4
      with:
        host: ${{ secrets.GCE_INSTANCE_HOST }}
        user: ${{ secrets.GCE_USER }}
        # key: ${{ secrets.GCE_SSH_KEY }}
        first_ssh: touch text1.txt
        scp: ./sample.txt => ./build/sample.txt
